/** ダミーデータの素材。実在の個人・組織を特定しないよう、一般的な語の組み合わせだけを使う */

/** [表記, ひらがな, ローマ字] */
export type JaName = readonly [string, string, string];

export const JA_FAMILY_NAMES: readonly JaName[] = [
  ['佐藤', 'さとう', 'sato'],
  ['鈴木', 'すずき', 'suzuki'],
  ['高橋', 'たかはし', 'takahashi'],
  ['田中', 'たなか', 'tanaka'],
  ['伊藤', 'いとう', 'ito'],
  ['渡辺', 'わたなべ', 'watanabe'],
  ['山本', 'やまもと', 'yamamoto'],
  ['中村', 'なかむら', 'nakamura'],
  ['小林', 'こばやし', 'kobayashi'],
  ['加藤', 'かとう', 'kato'],
  ['吉田', 'よしだ', 'yoshida'],
  ['山田', 'やまだ', 'yamada'],
  ['佐々木', 'ささき', 'sasaki'],
  ['山口', 'やまぐち', 'yamaguchi'],
  ['松本', 'まつもと', 'matsumoto'],
  ['井上', 'いのうえ', 'inoue'],
  ['木村', 'きむら', 'kimura'],
  ['林', 'はやし', 'hayashi'],
  ['斎藤', 'さいとう', 'saito'],
  ['清水', 'しみず', 'shimizu'],
  ['森', 'もり', 'mori'],
  ['池田', 'いけだ', 'ikeda'],
  ['橋本', 'はしもと', 'hashimoto'],
  ['阿部', 'あべ', 'abe'],
  ['石川', 'いしかわ', 'ishikawa'],
  ['前田', 'まえだ', 'maeda'],
  ['藤田', 'ふじた', 'fujita'],
  ['岡田', 'おかだ', 'okada'],
  ['後藤', 'ごとう', 'goto'],
  ['長谷川', 'はせがわ', 'hasegawa'],
];

export const JA_GIVEN_NAMES: readonly JaName[] = [
  ['太郎', 'たろう', 'taro'],
  ['花子', 'はなこ', 'hanako'],
  ['健太', 'けんた', 'kenta'],
  ['美咲', 'みさき', 'misaki'],
  ['翔太', 'しょうた', 'shota'],
  ['陽菜', 'ひな', 'hina'],
  ['大輔', 'だいすけ', 'daisuke'],
  ['結衣', 'ゆい', 'yui'],
  ['拓也', 'たくや', 'takuya'],
  ['愛', 'あい', 'ai'],
  ['蓮', 'れん', 'ren'],
  ['彩花', 'あやか', 'ayaka'],
  ['直樹', 'なおき', 'naoki'],
  ['優子', 'ゆうこ', 'yuko'],
  ['誠', 'まこと', 'makoto'],
  ['恵', 'めぐみ', 'megumi'],
  ['和也', 'かずや', 'kazuya'],
  ['真理', 'まり', 'mari'],
  ['隆', 'たかし', 'takashi'],
  ['千尋', 'ちひろ', 'chihiro'],
  ['悠斗', 'ゆうと', 'yuto'],
  ['莉子', 'りこ', 'riko'],
  ['啓介', 'けいすけ', 'keisuke'],
  ['菜々子', 'ななこ', 'nanako'],
  ['剛', 'つよし', 'tsuyoshi'],
  ['由美', 'ゆみ', 'yumi'],
  ['浩二', 'こうじ', 'koji'],
  ['紗希', 'さき', 'saki'],
  ['大和', 'やまと', 'yamato'],
  ['美穂', 'みほ', 'miho'],
];

export const EN_FIRST_NAMES: readonly string[] = [
  'James',
  'Mary',
  'Robert',
  'Patricia',
  'John',
  'Jennifer',
  'Michael',
  'Linda',
  'David',
  'Elizabeth',
  'William',
  'Barbara',
  'Richard',
  'Susan',
  'Joseph',
  'Jessica',
  'Thomas',
  'Sarah',
  'Daniel',
  'Karen',
  'Matthew',
  'Nancy',
  'Andrew',
  'Emily',
  'Kevin',
  'Laura',
  'Brian',
  'Rachel',
  'Steven',
  'Olivia',
];

export const EN_LAST_NAMES: readonly string[] = [
  'Smith',
  'Johnson',
  'Williams',
  'Brown',
  'Jones',
  'Miller',
  'Davis',
  'Wilson',
  'Anderson',
  'Taylor',
  'Thomas',
  'Moore',
  'Martin',
  'Jackson',
  'Thompson',
  'White',
  'Harris',
  'Clark',
  'Lewis',
  'Walker',
  'Hall',
  'Allen',
  'Young',
  'King',
  'Wright',
  'Scott',
  'Green',
  'Baker',
  'Adams',
  'Nelson',
];

/** [都道府県, 市区] */
export const JA_PREF_CITIES: readonly (readonly [string, string])[] = [
  ['東京都', '新宿区'],
  ['東京都', '渋谷区'],
  ['東京都', '千代田区'],
  ['大阪府', '大阪市北区'],
  ['愛知県', '名古屋市中区'],
  ['北海道', '札幌市中央区'],
  ['福岡県', '福岡市博多区'],
  ['神奈川県', '横浜市西区'],
  ['京都府', '京都市中京区'],
  ['兵庫県', '神戸市中央区'],
  ['宮城県', '仙台市青葉区'],
  ['広島県', '広島市中区'],
  ['埼玉県', 'さいたま市浦和区'],
  ['千葉県', '千葉市中央区'],
  ['静岡県', '静岡市葵区'],
  ['新潟県', '新潟市中央区'],
];

export const JA_TOWNS: readonly string[] = [
  '中央',
  '本町',
  '緑町',
  '栄町',
  '新町',
  '桜ヶ丘',
  '駅前',
  '大手町',
  '港町',
  '青葉台',
  '東',
  '西',
];

export const JA_COMPANY_WORDS: readonly string[] = [
  'アオバ',
  'ミライ',
  'ヒカリ',
  'サクラ',
  'ハルカ',
  'ソラ',
  'ミナト',
  'カエデ',
  'ユメ',
  'ホシゾラ',
  'ノゾミ',
  'ツバサ',
];

export const JA_COMPANY_SUFFIXES: readonly string[] = [
  '商事',
  '工業',
  'システム',
  'ソリューションズ',
  'テクノロジー',
  '食品',
  '建設',
  '物産',
];

export const EN_STREETS: readonly string[] = [
  'Maple',
  'Oak',
  'Cedar',
  'Pine',
  'Elm',
  'Washington',
  'Lake',
  'Hill',
  'Sunset',
  'Park',
  'Main',
  'River',
  'Highland',
  'Church',
  'Willow',
  'Spring',
];

export const EN_STREET_SUFFIXES: readonly string[] = [
  'St',
  'Ave',
  'Rd',
  'Blvd',
  'Ln',
];

/** [市, 州略称] */
export const EN_CITY_STATES: readonly (readonly [string, string])[] = [
  ['Portland', 'OR'],
  ['Austin', 'TX'],
  ['Denver', 'CO'],
  ['Columbus', 'OH'],
  ['Madison', 'WI'],
  ['Raleigh', 'NC'],
  ['Boise', 'ID'],
  ['Tampa', 'FL'],
  ['Seattle', 'WA'],
  ['Albany', 'NY'],
  ['Phoenix', 'AZ'],
  ['Atlanta', 'GA'],
];

export const EN_COMPANY_WORDS: readonly string[] = [
  'Northwind',
  'Bluebird',
  'Evergreen',
  'Summit',
  'Harbor',
  'Lighthouse',
  'Maple Leaf',
  'Redwood',
  'Silverline',
  'Brightside',
  'Clearwater',
  'Ironwood',
];

export const EN_COMPANY_SUFFIXES: readonly string[] = [
  'Labs',
  'Systems',
  'Partners',
  'Group',
  'Industries',
  'Solutions',
  'Works',
  'Co.',
];

/** 北米の電話番号の市外局番（ダミー番号 555-01XX と組み合わせる） */
export const EN_AREA_CODES: readonly string[] = [
  '212',
  '312',
  '415',
  '512',
  '617',
  '206',
  '303',
  '404',
];

/** RFC 2606 で例示用に予約されたドメイン */
export const EMAIL_DOMAINS: readonly string[] = [
  'example.com',
  'example.net',
  'example.org',
];
