import type { FaqContent } from '../faq';

export const faq: FaqContent = {
  ja: [
    {
      question: 'RSA・ECDSA・Ed25519はどれを選べばよいですか？',
      answer:
        '互換性を最優先するならRSA-2048以上、短い鍵と速度を重視するならECDSA P-256かEd25519が目安です。接続先のシステムが対応している方式を確認して選んでください。',
    },
    {
      question: 'Ed25519を選ぶとエラーになります。',
      answer:
        'Ed25519はWeb Crypto APIへの対応が新しく、古いブラウザでは使えません。ブラウザを最新版に更新するか、ECDSA（P-256）などを選んでください。',
    },
    {
      question: '生成した鍵はOpenSSHの ssh-keygen と同じ形式ですか？',
      answer:
        'いいえ。公開鍵はSPKI、秘密鍵はPKCS#8のPEM形式です。OpenSSH独自の形式（id_ed25519 や ssh-rsa で始まる公開鍵）では出力しません。OpenSSLなどでそのまま読み込めます。',
    },
    {
      question: '生成した鍵はサーバーに送られたり保存されたりしますか？',
      answer:
        'いいえ。鍵はブラウザ内のWeb Crypto APIで生成され、どこにも送信・保存されません。ページを閉じると消えるため、必要な鍵は先にコピーか保存をしてください。',
    },
  ],
  en: [
    {
      question: 'Which should I choose: RSA, ECDSA, or Ed25519?',
      answer:
        'For maximum compatibility use RSA-2048 or larger; for short keys and speed, ECDSA P-256 or Ed25519 are good choices. Check which algorithms the system you connect to supports.',
    },
    {
      question: 'Choosing Ed25519 shows an error.',
      answer:
        'Ed25519 support in the Web Crypto API is recent and missing from older browsers. Update your browser or pick ECDSA (P-256) instead.',
    },
    {
      question: 'Are the keys in the same format as OpenSSH ssh-keygen?',
      answer:
        'No. Public keys are SPKI and private keys are PKCS#8, both as PEM. The OpenSSH-specific formats (id_ed25519, or public keys starting with ssh-rsa) are not produced. OpenSSL and similar tools can read the PEM directly.',
    },
    {
      question: 'Are the generated keys sent to a server or stored?',
      answer:
        'No. Keys are generated by the Web Crypto API in your browser and are neither sent nor stored anywhere. They vanish when you close the page, so copy or save the keys you need first.',
    },
  ],
};
